set_dial_value:
  target:
    entity:
      integration: vu1_dials
  fields:
    value:
      required: true
      example: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_dial_backlight:
  target:
    entity:
      integration: vu1_dials
  fields:
    red:
      required: true
      example: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    green:
      required: true
      example: 25
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    blue:
      required: true
      example: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    white:
      required: false
      example: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_dial_name:
  target:
    entity:
      integration: vu1_dials
  fields:
    name:
      required: true
      example: "CPU Usage"
      selector:
        text:

set_dial_image:
  target:
    entity:
      integration: vu1_dials
  fields:
    media_content_id:
      required: true
      selector:
        media:
          accept:
            - "image/*"

reload_dial:
  target:
    entity:
      integration: vu1_dials
