name: HACS Validator

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: HACS Action
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: "brands"
          comment: true

  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
